ATMEL: USB device task
USB device task
Functions
void usb_device_task_init (void)
void usb_start_device (void)
void usb_device_task (void)
Variables
bit usb_suspended
Public : (bit) usb_suspended usb_suspended is set to TRUE when USB is in suspend mode usb_suspended is set to FALSE otherwise /.
bit usb_connected
Public : (bit) usb_connected usb_connected is set to TRUE when VBUS has been detected usb_connected is set to FALSE otherwise /.
Function Documentation
void usb_device_task_init (void)
This function initializes the USB device controller.
This function enables the USB controller and init the USB interrupts. The aim is to allow the USB connection detection in order to send the appropriate USB event to the operating mode manager.
Parameters:
none
Returns:
none
This function initializes the USB device controller and system interrupt This function enables the USB controller and init the USB interrupts. The aim is to allow the USB connection detection in order to send the appropriate USB event to the operating mode manager.
Parameters:
none
Returns:
none
/
Definition at line 106 of file usb_device_task.c.
References Usb_disable, Usb_enable, and Usb_vbus_sense_init.
{
   Usb_disable();
   Usb_enable();
#if (VBUS_SENSING_IO == ENABLED)
   Usb_vbus_sense_init();   // init. the I/O used for Vbus sensing
#endif
}
void usb_start_device (void)
This function initializes the USB device controller This function enables the USB controller and init the USB interrupts. The aim is to allow the USB connection detection in order to send the appropriate USB event to the operating mode manager. Start device function is executed once VBUS connection has been detected either by the VBUS change interrupt either by the VBUS high level
Parameters:
none
Returns:
none
Definition at line 128 of file usb_device_task.c.
References Usb_attach, Usb_enable_reset_interrupt, Usb_enable_suspend_interrupt, Usb_freeze_clock, usb_init_device(), Usb_reset_all_system, Usb_reset_macro_only, Usb_unfreeze_clock, and Wait_pll_ready.
{
   Usb_freeze_clock();
#ifndef USE_USB_AUTOBAUD
   Pll_start_auto();
#else
   usb_autobaud();
#endif
   Wait_pll_ready();
   Disable_interrupt();
   Usb_unfreeze_clock();
   Usb_attach();
#if (USB_RESET_CPU == ENABLED)
   Usb_reset_all_system();
#else
   Usb_reset_macro_only();
#endif
   usb_init_device();         // configure the USB controller EP0
   Usb_enable_suspend_interrupt();
   Usb_enable_reset_interrupt();
   Enable_interrupt();
}
void usb_device_task (void)
Entry point of the USB device mamagement This function is the entry point of the USB management. Each USB event is checked here in order to launch the appropriate action. If a Setup request occurs on the Default Control Endpoint, the usb_process_request() function is call in the usb_standard_request.c file
Parameters:
none
Returns:
none
Definition at line 161 of file usb_device_task.c.
References EP_CONTROL, EVT_USB_RESET, FALSE, Is_usb_event, Is_usb_receive_setup, Is_usb_vbus_off, Is_usb_vbus_on, Stop_pll, TRUE, Usb_ack_event, usb_configuration_nb, usb_connected, Usb_detach, Usb_disable, Usb_enable, usb_process_request(), Usb_reset_endpoint, Usb_select_endpoint, usb_start_device(), and Usb_vbus_on_action.
{
   if (usb_connected == FALSE)
   {
     #if (VBUS_SENSING_IO == ENABLED)
     if (Is_usb_vbus_on())    // check if Vbus ON to attach
     {
       Usb_enable();
       usb_connected = TRUE;
       usb_start_device();
       Usb_vbus_on_action();
     }
     #else
     usb_connected = TRUE;    // attach if application is not self-powered
     usb_start_device();
     Usb_vbus_on_action();
     #endif
   }
   #if (VBUS_SENSING_IO == ENABLED)
   if ((usb_connected == TRUE) && Is_usb_vbus_off())  // check if Vbus OFF to detach
   {
     Usb_detach();
     Usb_disable();
     Stop_pll();
     usb_connected = FALSE;
     usb_configuration_nb=0;
   }
   #endif
   if(Is_usb_event(EVT_USB_RESET))
   {
      Usb_ack_event(EVT_USB_RESET);
      Usb_reset_endpoint(0);
      usb_configuration_nb=0;
   }
   // Here connection to the device enumeration process
   Usb_select_endpoint(EP_CONTROL);
   if (Is_usb_receive_setup())
   {
      usb_process_request();
   }
}
Variable Documentation
bit usb_suspended
Public : (bit) usb_suspended usb_suspended is set to TRUE when USB is in suspend mode usb_suspended is set to FALSE otherwise /.
Definition at line 79 of file usb_device_task.c.
bit usb_connected
Public : (bit) usb_connected usb_connected is set to TRUE when VBUS has been detected usb_connected is set to FALSE otherwise /.
Definition at line 72 of file usb_device_task.c.