ATMEL: uart_usb_lib.c File Reference
uart_usb_lib.c File Reference
#include "config.h"
#include "lib_mcu/usb/usb_drv.h"
#include "usb_descriptors.h"
#include "uart_usb_lib.h"
Functions
void uart_usb_init (void)
bit uart_usb_test_hit (void)
char uart_usb_getchar (void)
bit uart_usb_tx_ready (void)
int uart_usb_putchar (int data_to_send)
void uart_usb_send_buffer (U8 *buffer, U8 nb_data)
Variables
Uchar rx_counter
Detailed Description
This file controls the UART USB functions.
Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: AT90USB162, AT90USB82
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file uart_usb_lib.c.
Function Documentation
void uart_usb_init (void)
Initializes the uart_usb library
Definition at line 64 of file uart_usb_lib.c.
{
  rx_counter = 0;
}
bit uart_usb_test_hit (void)
This function checks if a character has been received on the USB bus.
Returns:
bit (true if a byte is ready to be read)
Definition at line 74 of file uart_usb_lib.c.
Referenced by cdc_task(), and uart_usb_getchar().
{
  if(!Is_device_enumerated())
     return FALSE;
  if (!rx_counter)
  {
    Usb_select_endpoint(RX_EP);
    if (Is_usb_receive_out())
    {
      rx_counter = Usb_byte_counter();
      if (!rx_counter)
      {
        Usb_ack_receive_out();
      }
    }
  }
  return (rx_counter!=0);
}
char uart_usb_getchar (void)
This function reads one byte from the USB bus If one byte is present in the USB fifo, this byte is returned. If no data is present in the USB fifo, this function waits for USB data.
Returns:
U8 byte received
Definition at line 102 of file uart_usb_lib.c.
Referenced by cdc_task(), and cdc_task_init().
{
  register Uchar data_rx;
  Usb_select_endpoint(RX_EP);
  if (!rx_counter) while (!uart_usb_test_hit());
  data_rx=Usb_read_byte();
  rx_counter--;
  if (!rx_counter) Usb_ack_receive_out();
  return data_rx;
}
bit uart_usb_tx_ready (void)
This function checks if the USB emission buffer is ready to accept at at least 1 byte
Returns:
Boolean. TRUE if the firmware can write a new byte to transmit.
Definition at line 121 of file uart_usb_lib.c.
{
  if(!Is_device_enumerated())
     return FALSE;
  if (!Is_usb_write_enabled())
  {
    return FALSE;
  }
  return TRUE;
}
int uart_usb_putchar (int data_to_send)
This function fills the USB transmit buffer with the new data. This buffer is sent if complete. To flush this buffer before waiting full, launch the uart_usb_flush() function.
Parameters:
data_to_send
Returns:
Definition at line 142 of file uart_usb_lib.c.
{
   uart_usb_send_buffer((U8*)&data_to_send, 1);
   return data_to_send;
}
void uart_usb_send_buffer (U8 * buffer, U8 nb_data)
This function transmits a ram buffer content to the USB. This function is mode efficient in term of USB bandwith transfer.
Parameters:
U8 *buffer : the pointer to the RAM buffer to be sent
data_to_send : the number of data to be sent
Definition at line 157 of file uart_usb_lib.c.
Referenced by uart_usb_putchar(), and usart_receive_interrupt().
{
   U8 zlp;
  if(!Is_device_enumerated())
     return;
   // Compute if zlp required
   if(nb_data%TX_EP_SIZE)
   { zlp=FALSE;}
   else { zlp=TRUE; }
   Usb_select_endpoint(TX_EP);
   while (nb_data)
   {
      while(Is_usb_write_enabled()==FALSE); // Wait Endpoint ready
      while(Is_usb_write_enabled() && nb_data)
      {
         Usb_write_byte(*buffer);
         buffer++;
         nb_data--;
   }
      Usb_ack_in_ready();
   }
   if(zlp)
   {
      while(Is_usb_write_enabled()==FALSE); // Wait Endpoint ready
      Usb_ack_in_ready();
}
}
Variable Documentation
Uchar rx_counter
Definition at line 57 of file uart_usb_lib.c.