ATMEL: cdc_task.c File Reference
cdc_task.c File Reference
#include "config.h"
#include "conf_usb.h"
#include "cdc_task.h"
#include "lib_mcu/usb/usb_drv.h"
#include "usb_descriptors.h"
#include "modules/usb/device_chap9/usb_standard_request.h"
#include "usb_specific_request.h"
#include "lib_mcu/uart/uart_lib.h"
#include "uart_usb_lib.h"
#include "lib_mcu/util/start_boot.h"
#include <stdio.h>
Functions
void cdc_task_init (void)
void cdc_task (void)
void sof_action ()
__interrupt void usart_receive_interrupt ()
Variables
volatile U8 cpt_sof
U8 rx_counter
U8 tx_counter
volatile U8 usb_request_break_generation
S_line_coding line_coding
S_line_status line_status
S_serial_state serial_state
volatile U8 rs2usb [10]
Detailed Description
This file manages the CDC task.
Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: AT90USB162, AT90USB82
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file cdc_task.c.
Function Documentation
void cdc_task_init (void)
This function initializes the hardware ressources required for CDC demo.
Parameters:
none
Returns:
none
/
Definition at line 89 of file cdc_task.c.
References Hwb_button_init, Joy_init, Leds_init, Uart_enable_it_rx, uart_init(), uart_usb_getchar(), uart_usb_putchar, and Usb_enable_sof_interrupt.
{
   uart_init();
   Uart_enable_it_rx();
   Leds_init();
   Joy_init();
   Hwb_button_init();
   Usb_enable_sof_interrupt();
#ifdef __GNUC__
    fdevopen((int (*)(char, FILE*))(uart_usb_putchar),(int (*)(FILE*))uart_usb_getchar); //for printf redirection
#endif
}
void cdc_task (void)
Entry point of the uart cdc management This function links the uart and the USB bus.
Parameters:
none
Returns:
none
Definition at line 111 of file cdc_task.c.
References S_serial_state::bDCD, S_serial_state::bDSR, cdc_update_serial_state(), cpt_sof, S_line_status::DTR, FALSE, Is_btn_left, Is_btn_middle, Is_device_enumerated, Is_joy_down, Is_joy_left, Is_joy_right, Is_joy_up, Led2_toggle, Led3_toggle, REPEAT_KEY_PRESSED, rx_counter, TRUE, uart_putchar(), Uart_tx_ready, uart_usb_getchar(), uart_usb_test_hit(), and usb_request_break_generation.
{
   if(Is_device_enumerated() && line_status.DTR) //Enumeration processs OK and COM port openned ?
        {
      if (Uart_tx_ready())    //USART free ?
      {
         if (uart_usb_test_hit())   // Something received from the USB ?
         {
             while (rx_counter)
            {
               uart_putchar(uart_usb_getchar());   // loop back USB to USART
               Led3_toggle();
            }
         }
      }
      if ( cpt_sof>=REPEAT_KEY_PRESSED)   //Debounce joystick events
      {
         if (Is_btn_middle()){
            printf ("Select Pressed !\r\n");
         }
         if (Is_joy_right()) {
            printf ("Right Pressed !\r\n");
            serial_state.bDCD = TRUE;
         }
         else
            serial_state.bDCD = FALSE;
         if (Is_joy_left()) {
            printf ("Left Pressed !\r\n");
            serial_state.bDSR = TRUE;
         }
         else
            serial_state.bDSR = FALSE;
         if (Is_joy_down())
         printf ("Down Pressed !\r\n");
         if (Is_joy_up())
         printf ("Up Pressed !\r\n");
         if(Is_btn_left())
         printf("Hello from AT90USBXXX !\r\n");
         cdc_update_serial_state();
      }
      if(usb_request_break_generation==TRUE)
      {
         usb_request_break_generation=FALSE;
         Led2_toggle();
      }
   }
}
__interrupt void usart_receive_interrupt ()
Uart Receive interrupt subroutine
Parameters:
none
Returns:
none
Definition at line 193 of file cdc_task.c.
References FALSE, Is_device_enumerated, Is_usb_write_enabled, rs2usb, TX_EP, Uart_get_byte, Uart_rx_ready, uart_usb_send_buffer(), Usb_get_selected_endpoint, and Usb_select_endpoint.
{
   U8 i=0;
   U8 save_ep;
   if(Is_device_enumerated())
   {
      save_ep=Usb_get_selected_endpoint();
      Usb_select_endpoint(TX_EP);
      do
      {
         if(Uart_rx_ready())
         {
            rs2usb[i]=Uart_get_byte();
            i++;
         }
      }while(Is_usb_write_enabled()==FALSE );
      uart_usb_send_buffer((U8*)&rs2usb,i);
      Usb_select_endpoint(save_ep);
   }
}
Variable Documentation
volatile U8 cpt_sof
Definition at line 70 of file cdc_task.c.
Referenced by cdc_task(), and sof_action().
U8 rx_counter
Definition at line 57 of file uart_usb_lib.c.
Referenced by cdc_task(), uart_usb_getchar(), uart_usb_init(), and uart_usb_test_hit().
U8 tx_counter
volatile U8 usb_request_break_generation
Definition at line 77 of file usb_specific_request.c.
Referenced by cdc_send_break(), and cdc_task().
S_line_coding line_coding
Definition at line 74 of file cdc_task.c.
S_line_status line_status
Definition at line 75 of file cdc_task.c.
S_serial_state serial_state
Definition at line 76 of file cdc_task.c.
volatile U8 rs2usb[10]
Definition at line 78 of file cdc_task.c.
Referenced by usart_receive_interrupt().