ATMEL: usb_specific_request.h File Reference
usb_specific_request.h File Reference
#include "config.h"
Data Structures
struct S_line_coding
union S_line_status
union S_serial_state
Functions
Bool usb_user_read_request (U8, U8)
This function checks the specific request and if known then processes it
void usb_user_endpoint_init (U8)
U8 usb_user_interface_get (U16 wInterface)
void usb_user_interface_reset (U16 wInterface, U8 alternate_setting)
Bool usb_user_get_descriptor (U8, U8)
This function fills the global descriptor.
void cdc_get_line_coding ()
cdc_get_line_coding.
void cdc_set_line_coding ()
cdc_set_line_coding.
void cdc_set_control_line_state (U16)
cdc_set_control_line_state.
void cdc_send_break (U16)
Bool cdc_update_serial_state ()
cdc_update_serial_state.
Variables
code
S_usb_device_descriptor usb_dev_desc
code
S_usb_user_configuration_descriptor usb_conf_desc
code
S_usb_manufacturer_string_descriptor usb_user_manufacturer_string_descriptor
code
S_usb_product_string_descriptor usb_user_product_string_descriptor
code S_usb_serial_number usb_user_serial_number
code S_usb_language_id usb_user_language_id
Detailed Description
Specific enumeration process requests header file - Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: AT90USB162, AT90USB82
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file usb_specific_request.h.
Function Documentation
Bool usb_user_read_request (U8 type, U8 request)
This function checks the specific request and if known then processes it
Parameters:
type corresponding at bmRequestType (see USB specification)
request corresponding at bRequest (see USB specification)
Returns:
TRUE, when the request is processed
FALSE, if the request is'nt know (STALL handshake is managed by the main standard request function).
Definition at line 90 of file usb_specific_request.c.
References cdc_get_line_coding(), cdc_send_break(), cdc_set_control_line_state(), cdc_set_line_coding(), FALSE, LSB, MSB, SETUP_CDC_GET_LINE_CODING, SETUP_CDC_SEND_BREAK, SETUP_CDC_SET_CONTROL_LINE_STATE, SETUP_CDC_SET_LINE_CODING, TRUE, Usb_read_byte, USB_SETUP_GET_CLASS_INTER, and USB_SETUP_SET_CLASS_INTER.
{
   U16 wValue;
   LSB(wValue) = Usb_read_byte();
   MSB(wValue) = Usb_read_byte();
   //** Specific request from Class CDC
   if( USB_SETUP_SET_CLASS_INTER == type )
   {
      switch( request )
      {
         case SETUP_CDC_SET_LINE_CODING:
         cdc_set_line_coding();
         return TRUE;
         break;
         case SETUP_CDC_SET_CONTROL_LINE_STATE:
         cdc_set_control_line_state(wValue); // according cdc spec 1.1 chapter 6.2.14
         return TRUE;
         break;
         case SETUP_CDC_SEND_BREAK:
         cdc_send_break(wValue);             // wValue contains break lenght
         return TRUE;
         break;
      }
   }
   if( USB_SETUP_GET_CLASS_INTER == type )
   {
      switch( request )
      {
         case SETUP_CDC_GET_LINE_CODING:
         cdc_get_line_coding();
         return TRUE;
         break;
      }
   }
   return FALSE;  // No supported request
}
void usb_user_endpoint_init (U8 conf_nb)
This function configures the endpoints
Parameters:
conf_nb configuration number choosed by USB host
Definition at line 136 of file usb_specific_request.c.
References DIRECTION_IN, DIRECTION_OUT, INT_EP, NYET_ENABLED, ONE_BANK, RX_EP, SIZE_32, TX_EP, TYPE_BULK, TYPE_INTERRUPT, usb_configure_endpoint, and Usb_reset_endpoint.
{
  usb_configure_endpoint(INT_EP,        \
                         TYPE_INTERRUPT,\
                         DIRECTION_IN,  \
                         SIZE_32,       \
                         ONE_BANK,      \
                         NYET_ENABLED);
  usb_configure_endpoint(TX_EP,         \
                         TYPE_BULK,     \
                         DIRECTION_IN,  \
                         SIZE_32,       \
                         ONE_BANK,      \
                         NYET_ENABLED);
  usb_configure_endpoint(RX_EP,         \
                         TYPE_BULK,     \
                         DIRECTION_OUT, \
                         SIZE_32,       \
                         ONE_BANK,      \
                         NYET_ENABLED);
  Usb_reset_endpoint(INT_EP);
  Usb_reset_endpoint(TX_EP);
  Usb_reset_endpoint(RX_EP);
}
U8 usb_user_interface_get (U16 wInterface)
This function returns the interface alternate setting
Parameters:
wInterface Interface selected
Returns:
alternate setting configurated
Definition at line 171 of file usb_specific_request.c.
{
   return 0;  // Only one alternate setting possible for all interface
}
void usb_user_interface_reset (U16 wInterface, U8 alternate_setting)
This function selects (and resets) the interface alternate setting
Parameters:
wInterface Interface selected
alternate_setting alternate setting selected
Definition at line 182 of file usb_specific_request.c.
References INT_EP, INTERFACE0_NB, INTERFACE1_NB, RX_EP, TX_EP, Usb_disable_stall_handshake, Usb_reset_data_toggle, Usb_reset_endpoint, and Usb_select_endpoint.
{
   // default setting selected = reset data toggle
   if( INTERFACE0_NB == wInterface )
   {
      // Interface CDC ACM Com
      Usb_select_endpoint(INT_EP);
      Usb_disable_stall_handshake();
      Usb_reset_endpoint(INT_EP);
      Usb_reset_data_toggle();
   }
   if( INTERFACE1_NB == wInterface )
   {
      // Interface CDC ACM Data
      Usb_select_endpoint(TX_EP);
      Usb_disable_stall_handshake();
      Usb_reset_endpoint(TX_EP);
      Usb_reset_data_toggle();
      Usb_select_endpoint(RX_EP);
      Usb_disable_stall_handshake();
      Usb_reset_endpoint(RX_EP);
      Usb_reset_data_toggle();
   }
}
Bool usb_user_get_descriptor (U8 type, U8 string)
This function fills the global descriptor.
Parameters:
type corresponding at MSB of wValue (see USB specification)
string corresponding at LSB of wValue (see USB specification)
Returns:
FALSE, if the global descriptor no filled
Definition at line 215 of file usb_specific_request.c.
References S_usb_serial_number::bLength, S_usb_language_id::bLength, data_to_transfer, DESCRIPTOR_STRING, f_get_serial_string, FALSE, LANG_ID, pbuffer, SN_INDEX, SN_LENGTH, TRUE, usb_user_language_id, and usb_user_serial_number.
{
   switch(type)
   {
      case DESCRIPTOR_STRING:
      switch (string)
      {
         case LANG_ID:
         data_to_transfer = sizeof (usb_user_language_id);
         pbuffer = &(usb_user_language_id.bLength);
         return TRUE;
         break;
#if (USB_DEVICE_SN_USE==ENABLE)
         case SN_INDEX:
         data_to_transfer = sizeof (usb_user_serial_number);
         pbuffer = &(usb_user_serial_number.bLength);
#if (USE_DEVICE_SN_UNIQUE==ENABLE)
         f_get_serial_string=TRUE;
         data_to_transfer += (SN_LENGTH*4);
#endif
         return TRUE;
         break;
#endif
      }
      break;
   }
   return FALSE;
}
void cdc_get_line_coding (void)
cdc_get_line_coding.
This function manages reception of line coding parameters (baudrate...).
Parameters:
none
Returns:
none
Definition at line 253 of file usb_specific_request.c.
References S_line_coding::bCharFormat, S_line_coding::bDataBits, S_line_coding::bParityType, S_line_coding::dwDTERate, Is_usb_read_control_enabled, Is_usb_receive_out, LSB0, LSB1, LSB2, LSB3, Usb_ack_receive_out, Usb_ack_receive_setup, Usb_send_control_in, and Usb_write_byte.
{
     Usb_ack_receive_setup();
     Usb_write_byte(LSB0(line_coding.dwDTERate));
     Usb_write_byte(LSB1(line_coding.dwDTERate));
     Usb_write_byte(LSB2(line_coding.dwDTERate));
     Usb_write_byte(LSB3(line_coding.dwDTERate));
     Usb_write_byte(line_coding.bCharFormat);
     Usb_write_byte(line_coding.bParityType);
     Usb_write_byte(line_coding.bDataBits);
     Usb_send_control_in();
     while(!(Is_usb_read_control_enabled()));
     //Usb_clear_tx_complete();
   while(!Is_usb_receive_out());
   Usb_ack_receive_out();
}
void cdc_set_line_coding (void)
cdc_set_line_coding.
This function manages reception of line coding parameters (baudrate...).
Parameters:
none
Returns:
none
Definition at line 281 of file usb_specific_request.c.
References S_line_coding::bCharFormat, S_line_coding::bDataBits, S_line_coding::bParityType, S_line_coding::dwDTERate, Is_usb_read_control_enabled, Is_usb_receive_out, LSB0, LSB1, LSB2, LSB3, Uart_set_baudrate, Usb_ack_receive_out, Usb_ack_receive_setup, Usb_read_byte, and Usb_send_control_in.
{
   Usb_ack_receive_setup();
   while (!(Is_usb_receive_out()));
   LSB0(line_coding.dwDTERate) = Usb_read_byte();
   LSB1(line_coding.dwDTERate) = Usb_read_byte();
   LSB2(line_coding.dwDTERate) = Usb_read_byte();
   LSB3(line_coding.dwDTERate) = Usb_read_byte();
   line_coding.bCharFormat = Usb_read_byte();
   line_coding.bParityType = Usb_read_byte();
   line_coding.bDataBits = Usb_read_byte();
     Usb_ack_receive_out();
     Usb_send_control_in();                // send a ZLP for STATUS phase
     while(!(Is_usb_read_control_enabled()));
#ifdef UART_U2
   Uart_set_baudrate((line_coding.dwDTERate)/2);
#else
   Uart_set_baudrate(line_coding.dwDTERate);
#endif
}
void cdc_set_control_line_state (U16 state)
cdc_set_control_line_state.
This function manages the SET_CONTROL_LINE_LINE_STATE CDC request.
Todo:
Manages here hardware flow control...
Parameters:
none
Returns:
none
Definition at line 314 of file usb_specific_request.c.
References S_line_status::all, Is_usb_read_control_enabled, Usb_ack_receive_setup, and Usb_send_control_in.
{
     Usb_ack_receive_setup();
   Usb_send_control_in();
   line_status.all = state;
     while(!(Is_usb_read_control_enabled()));
}
void cdc_send_break (U16 break_duration)
This function manages the SEND_BREAK CDC request.
Todo:
Manages here hardware flow control...
Parameters:
break lenght
Definition at line 372 of file usb_specific_request.c.
References Is_usb_read_control_enabled, TRUE, Usb_ack_receive_setup, usb_request_break_generation, and Usb_send_control_in.
{
   Usb_ack_receive_setup();
    Usb_send_control_in();
   usb_request_break_generation=TRUE;
   while(!(Is_usb_read_control_enabled()));
}
Bool cdc_update_serial_state ()
cdc_update_serial_state.
This function checks if serial state has changed and updates host with that information.
Todo:
Return TRUE only if update was accepted by host, to detect need for resending
Parameters:
none
Returns:
TRUE if updated state was sent otherwise FALSE
upr: Added for hardware handshake support according cdc spec 1.1 chapter 6.3.5
Definition at line 336 of file usb_specific_request.c.
References S_serial_state::all, FALSE, INT_EP, Is_usb_write_enabled, LSB, MSB, SETUP_CDC_BN_SERIAL_STATE, TRUE, Usb_ack_in_ready, Usb_select_endpoint, USB_SETUP_GET_CLASS_INTER, and Usb_write_byte.
{
   if( serial_state_saved.all != serial_state.all)
   {
      serial_state_saved.all = serial_state.all;
      Usb_select_endpoint(INT_EP);
      if (Is_usb_write_enabled())
      {
         Usb_write_byte(USB_SETUP_GET_CLASS_INTER);   // bmRequestType
         Usb_write_byte(SETUP_CDC_BN_SERIAL_STATE);   // bNotification
         Usb_write_byte(0x00);   // wValue (zero)
         Usb_write_byte(0x00);
         Usb_write_byte(0x00);   // wIndex (Interface)
         Usb_write_byte(0x00);
         Usb_write_byte(0x02);   // wLength (data count = 2)
         Usb_write_byte(0x00);
         Usb_write_byte(LSB(serial_state.all));   // data 0: LSB first of serial state
         Usb_write_byte(MSB(serial_state.all));   // data 1: MSB follows
         Usb_ack_in_ready();
      }
      return TRUE;
   }
   return FALSE;
}
Variable Documentation
code S_usb_device_descriptor usb_dev_desc
Definition at line 69 of file usb_descriptors.c.
code S_usb_user_configuration_descriptor usb_conf_desc
Definition at line 88 of file usb_descriptors.c.
code S_usb_manufacturer_string_descriptor usb_user_manufacturer_string_descriptor
Definition at line 154 of file usb_descriptors.c.
code S_usb_product_string_descriptor usb_user_product_string_descriptor
Definition at line 163 of file usb_descriptors.c.
code S_usb_serial_number usb_user_serial_number
Definition at line 172 of file usb_descriptors.c.
code S_usb_language_id usb_user_language_id
Definition at line 186 of file usb_descriptors.c.